---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/jbovet/drone-clair

steps:
- name: build
  pull: if-not-exists
  image: golang:1.16
  commands:
  - go test -cover -coverprofile=coverage.out
  - go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a
  environment:
    CGO_ENABLED: 0

...
