workspace:
  base: /go
  path: src/github.com/jbovet/drone-clair

pipeline:
  build:
    image: golang:1.16
    environment:
      - CGO_ENABLED=0
    commands:
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a
